### ISSUE TITLE
MT5 version panel flashing when TF changes

### ISSUE THREAD

**Issue by paymanz** [EarnForex/PositionSizer#36] opened 2022-02-14 09:47 UTC
hi , on mt5 when panel is minimized switching timeframe causes a quick flash(panel become visible for a second).

**Comment by EarnForex** [comment] 2022-02-14 10:13
Yes, this happens because the indicator is re-initialized every time you change the timeframe. It has to re-create the panel and then minimize it. Does it cause any problems?

**Comment by paymanz** [comment] 2022-02-14 13:01
> Yes, this happens because the indicator is re-initialized every time you change the timeframe. It has to re-create the panel and then minimize it. Does it cause any problems?

not a big deal obviously (of curse it would be nice if it doesn't happen, if possible), in mt4 there is no such thing happening so that's why reported it.

thanks

**Comment by EarnForex** [comment] 2022-02-14 14:25
I will look into it, but I believe that's caused by MT5's general slowness when working with chart objects.

**Comment by EarnForex** [comment] 2023-03-29 18:20
Should be addressed in 3.03.

**Closed by EarnForex** 2023-03-29 18:20 UTC
