### ISSUE TITLE
Issue With MT4 Version of calculator

### ISSUE THREAD

**Issue by TecnoHands** [EarnForex/PositionSizer#45] opened 2022-07-04 22:08 UTC
Hello I don't how but, when apply your indicator the graphic don't show me all price, in the contrarian manner it shows shortly
I Attach a Screenshot.

In the image you can see in price don't showing last pip and the pipete
![Captura](https://user-images.githubusercontent.com/16818257/177220840-038aa98f-54ad-433e-9fb2-753c25705dd9.PNG)
l

And in a new chart without your indicator price showing correctly
![Captura1](https://user-images.githubusercontent.com/16818257/177220932-a46158ce-f6a4-46b0-ae3f-4b45b58140c0.PNG)

It's how if the indicator expands the chart to the right into the MT4
And my congrats is a powerfull too

**Comment by EarnForex** [comment] 2022-07-05 09:34
Hello!

That's the first time I see something like that...
Is that running on Windows?
Did you try attaching a Position Size Calculator to a bare chart, without any other indicators/EAs? Was the result the same?

**Comment by TecnoHands** [comment] 2022-07-14 01:17
Hello, yes running in windows, and without indicators has the same bug

![image](https://user-images.githubusercontent.com/16818257/178866483-3b9abb28-f98c-4a6d-98d2-5dbd49301db3.png)

**Comment by EarnForex** [comment] 2022-07-14 10:10
Hello!

Yes, now I was able to reproduce the issue myself. I will look into it and will try to fix it. Thank you for reporting this!

**Comment by EarnForex** [comment] 2022-07-16 12:02
Seems to be caused by a fix to [this issue](https://github.com/EarnForex/PositionSizeCalculator/issues/35).

**Comment by EarnForex** [comment] 2022-07-26 14:14
Almost fixed in 3.00. Not sure if possible to fix entirely in MT4 (appears to be some glitch with their price scale).

**Closed by EarnForex** 2022-07-26 14:14 UTC

**Comment by onedao** [comment] 2022-10-11 09:11
Best Regards ,Jianhua ZhuangXishi Co.,Ltd.+86 188 7652 3758  Phone+86 0595 8600 1500 Telhttp://www.xishigroup.com
